// src/components/header.component.svelte
<script lang="ts">
	import { t } from '../shared/services/i18n.service';
	import I18n from './i18n.component.svelte';
</script>

<header class="flex justify-between items-center mt-2">
	<a href="/">
		<img src="/favicon.png" alt="virak's logo" width="64" height="64" />
	</a>
	<div class="flex items-center gap-4">
		<a href="/blogs" class="font-bold uppercase">{$t('nav.blogs')}</a>
		<I18n />
	</div>
</header>

// packages/web/modules/core/components/header.component.tsx
'use client'

import Link from 'next/link'
import { FaGithub } from 'react-icons/fa6'

export const HeaderComponent = () => {
	return (
		<header className='flex justify-between items-center py-2'>
			<div>
				<FaGithub className='w-7 h-7' />
			</div>
			<div className='flex items-center gap-4'>
				<Link href='/blogs'>Blogs</Link>
			</div>
		</header>
	)
}
